In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn import preprocessing

In [2]:
pd.options.display.max_rows = 100
pd.options.display.max_columns = 50

In [11]:
df1=pd.read_csv('total1101.csv')
df2=pd.read_csv('combine_source_host.csv')
df3=pd.read_csv('profile_without_YN.csv')

In [12]:
df=pd.merge(df1,df2,how='left',on='Pseudo_ClientID')
df=pd.merge(df,df3,how='left',on='Pseudo_ClientID')

In [13]:
df.head()

,Pseudo_ClientID,day_counts_max,day_counts_min,day_counts_mean,day_counts_count,day_counts_std,Issue_YN,weekday_Monday,weekday_Tuesday,weekday_Wednesday,weekday_Thursday,weekday_Friday,weekday_Saturday,weekday_Sunday,total,Mondayratio,Tuesdayratio,Wednesdayratio,Thursdayratio,Fridayratio,Saturdayratio,Sundayratio,Duration_max,Duration_min,Duration_mean,...,payx_Serv20_ratio_y,payx_Serv21_ratio_y,payx_Serv22_ratio_y,payx_Serv23_ratio_y,payx_Serv24_ratio_y,payx_Serv25_ratio_y,payx_Serv26_ratio_y,Unnamed: 0,ACTV_JOB_COUNT_y,ACTV_WRKR_COUNT_y,WRKR_COUNT_y,BANK_COUNT_y,CHECK_COUNT_y,CLT_PAYCOMP_COUNT_y,CLT_TAX_COUNT_y,GL_ACCT_COUNT_y,JOB_COUNT_y,LOCATION_COUNT_y,ORG_UNIT_COUNT_y,PAYRUN_COUNT_y,PAY_PERIOD_COUNT_y,POSITION_COUNT_y,WRKR_PAY_COMP_AVG_y,WRKR_TAX_AVG_y,NULL_COUNT_y
0,00022C46-9142-4469-AEF6-E235802CBE11,17,13,15.00,2,2.828427,0,0.0,13.0,0.0,0.0,17.0,0.0,0.0,30.0,0.000000,0.433333,0.000000,0.000000,0.566667,0.0,0.0,4169,17,1276.233333,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0,NaN,-5.062429,-4.657624,-0.796265,-4.783789,-4.748977,0.511194,NaN,NaN,-1.282486,-2.503428,9.752293,8.621629,NaN,2.103113,-3.171023,4
1,00029786-E7BB-4442-90B1-C48A8211F0DF,12,2,7.50,4,4.434712,0,0.0,0.0,20.0,10.0,0.0,0.0,0.0,30.0,0.000000,0.000000,0.666667,0.333333,0.000000,0.0,0.0,6165,21,1510.600000,...,0.200000,0.000000,0.0,0.000000,0.0,0.0,0.4,1,NaN,-4.910984,-4.683246,-0.796265,-4.712576,-8.855622,-5.042807,NaN,NaN,-1.757961,-2.590043,-4.732344,-5.018195,NaN,-9.702801,-11.337071,4
2,0002A30C-B22C-447C-ADAF-025BA827B2F3,41,27,32.75,4,5.909033,0,99.0,32.0,0.0,0.0,0.0,0.0,0.0,131.0,0.755725,0.244275,0.000000,0.000000,0.000000,0.0,0.0,105211,184,3644.625954,...,0.244275,0.000000,0.0,0.206107,0.0,0.0,0.0,2,NaN,-3.123944,-2.979369,-0.796265,-2.132149,-9.540063,-3.288912,NaN,NaN,-1.757961,-2.027047,32.030294,31.625009,NaN,-9.702801,9.078048,4
3,00042184-FF8D-4255-8201-FB782CFEA259,1,1,1.00,1,NaN,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,3048,3048,3048.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,3,NaN,-4.668674,-3.991447,-0.796265,-3.814034,-9.540063,-3.873543,NaN,NaN,-1.757961,-2.416813,13.688335,12.602983,NaN,NaN,4.995024,5
4,000477F9-3A91-479E-B10A-2C2BFA344360,26,12,18.20,5,6.723095,0,40.0,0.0,25.0,26.0,0.0,0.0,0.0,91.0,0.439560,0.000000,0.274725,0.285714,0.000000,0.0,0.0,6271,58,1946.659341,...,0.131868,0.153846,0.0,0.000000,0.0,0.0,0.0,4,NaN,-3.063366,-3.017803,1.385662,-3.009745,2.095431,-0.365754,NaN,NaN,-0.807011,-2.243584,41.161913,40.177547,NaN,2.103113,0.912001,4

In [14]:
df.to_csv('./total1101.csv',index=False)
df=df.fillna(-100)

In [15]:
train_x=df.iloc[:,1:]
train_x=train_x.drop('Issue_YN',axis=1)
train_y=df['Issue_YN']

In [16]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from scipy import interp
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import StratifiedKFold

In [57]:
clf = RandomForestClassifier(n_estimators=200, min_samples_leaf = 1)

In [58]:
scores = cross_val_score(clf,train_x,train_y, scoring='accuracy',cv=5)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.96 (+/- 0.00)

In [59]:
scores = cross_val_score(clf,train_x,train_y, scoring='f1',cv=5)
print("f1: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

f1: 0.47 (+/- 0.04)

In [60]:
scores = cross_val_score(clf,train_x,train_y, scoring='recall',cv=5)
print("recall: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

recall: 0.36 (+/- 0.03)